### ISSUE TITLE
42Intra API authentication

### ISSUE THREAD

**Issue by Gab-182** [Aztaro97/42-daily-dev#5]
The API key has expired,it should be regenerated from[here](https://github.com/Aztaro97/42-daily-dev/blob/169fecb8bae84a42bd8a1209a8e825c673f2c198/.env.exemple#L19)

[Here](https://github.com/Aztaro97/42-daily-dev/blob/169fecb8bae84a42bd8a1209a8e825c673f2c198/src/components/authModal/index.tsx#L48)

**Comment by Aztaro97** [comment]
Thanks you @Gab-182 , The new  API key was been updated ✅
